-- Optional manual SQL for Neon if you want to inspect/create the schema directly.
-- Prisma db push / Prisma migrate is the recommended path.

CREATE TYPE "Role" AS ENUM ('PATIENT', 'ADMIN');

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  "pinHash" TEXT NOT NULL,
  role "Role" NOT NULL DEFAULT 'PATIENT',
  name TEXT NOT NULL,
  age INTEGER,
  gender TEXT,
  conditions TEXT,
  "targetCarbs" DOUBLE PRECISION NOT NULL DEFAULT 80,
  "targetProteins" DOUBLE PRECISION NOT NULL DEFAULT 60,
  "targetFats" DOUBLE PRECISION NOT NULL DEFAULT 150,
  "targetCalories" DOUBLE PRECISION NOT NULL DEFAULT 2000,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS food_items (
  id TEXT PRIMARY KEY,
  "itemName" TEXT NOT NULL UNIQUE,
  carbohydrates DOUBLE PRECISION NOT NULL,
  proteins DOUBLE PRECISION NOT NULL,
  fats DOUBLE PRECISION NOT NULL,
  calories DOUBLE PRECISION NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS medical_records (
  id TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  date TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  weight DOUBLE PRECISION NOT NULL,
  height DOUBLE PRECISION NOT NULL,
  bmi DOUBLE PRECISION NOT NULL,
  "bpLow" DOUBLE PRECISION NOT NULL,
  "bpHigh" DOUBLE PRECISION NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS medical_records_user_date_idx ON medical_records ("userId", date);

CREATE TABLE IF NOT EXISTS food_logs (
  id TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  "foodItemId" TEXT NOT NULL REFERENCES food_items(id) ON DELETE RESTRICT,
  date TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "dishName" TEXT NOT NULL,
  "quantityGms" DOUBLE PRECISION NOT NULL,
  carbs DOUBLE PRECISION NOT NULL,
  proteins DOUBLE PRECISION NOT NULL,
  fats DOUBLE PRECISION NOT NULL,
  calories DOUBLE PRECISION NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS food_logs_user_date_idx ON food_logs ("userId", date);
CREATE INDEX IF NOT EXISTS food_logs_food_item_idx ON food_logs ("foodItemId");
